name: deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    needs: Build-Container-Image
    steps:
      - name: Update image tag for container alexohneander-zola in deployment.yaml
        uses: loveholidays/gitops-action-yaml-updater@v1.0
        with:
          mode: IMAGE_TAG
          container-name: alexohneander-zola
          new-image-tag: ${{ github.sha }}
          dir: deploy/
          files: deployment.yaml
