name: Build Docker Container
run-name: ${{ gitea.actor }} is building container
on: [push]

jobs:
  Build-Container-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: dind
          platforms: |
            linux/amd64
          # push: true
          # tags: |
          #   ${{ env.DOCKER_ORG }}/${{ steps.meta.outputs.REPO_NAME }}:${{ env.DOCKER_LATEST }}