name: Build Docker Container
run-name: ${{ gitea.actor }} is building container
on: [push]

jobs:
  Build-Container-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          DOCKER_HOST: tcp://127.0.0.1:2376
        with:
          context: .
          file: ./Dockerfile
          target: basic
          platforms: |
            linux/amd64
          # push: true
          # tags: |
          #   ${{ env.DOCKER_ORG }}/${{ steps.meta.outputs.REPO_NAME }}:${{ env.DOCKER_LATEST }}