name: Build Docker Container
run-name: ${{ gitea.actor }} is building container
on: [push]

jobs:
  Build-Container-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          export DOCKER_HOST=tcp://docker:2376/
          export DOCKER_TLS_CERTDIR="/certs"
          export DOCKER_TLS_VERIFY=1
          export DOCKER_CERT_PATH="/certs/client"
          docker context create builders
      # https://github.com/docker/setup-buildx-action
      # https://docs.docker.com/engine/reference/commandline/cli/#environment-variables
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          # buildkitd-flags: --debug
          endpoint: builders
        env:
          DOCKER_HOST: "tcp://docker:2376/"
          DOCKER_TLS_CERTDIR: "/certs"
          DOCKER_TLS_VERIFY: 1
          DOCKER_CERT_PATH: "/certs/client"
      - name: Build and push the image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: containers/test
        env:
          DOCKER_HOST: "tcp://docker:2376/"
          DOCKER_TLS_CERTDIR: "/certs"
          DOCKER_TLS_VERIFY: 1
          DOCKER_CERT_PATH: "/certs/client"