name: Build Docker Container
run-name: ${{ gitea.actor }} is building container
on: [push]

jobs:
  Build-Container-Image:
    runs-on: ubuntu-latest
    steps:
      - run: docker build -t alexohneander/alexohneander-zola:latest .
        env:
          DOCKER_HOST: unix:///var/run/docker.sock #"tcp://127.0.0.1:2376"